const CFG=window.METEO_FASSA_TRIPS,ROME="Europe/Rome";
let stations=[],forecastLocations=[],selectedZone="catinaccio",selectedDate=null;
const $=s=>document.querySelector(s);
function finite(v){return v!==null&&v!==undefined&&v!==""&&Number.isFinite(Number(v));}
function fmt(v,d=1){return finite(v)?Number(v).toFixed(d).replace(".",","):"—";}
function when(v){if(!v)return null;const d=new Date(v);return Number.isNaN(d.getTime())?null:d;}
function clock(v){const d=when(v);return d?new Intl.DateTimeFormat("it-IT",{timeZone:ROME,hour:"2-digit",minute:"2-digit"}).format(d):"—";}
function dayLabel(v){const d=new Date(`${v}T12:00:00`);return new Intl.DateTimeFormat("it-IT",{weekday:"short",day:"numeric",timeZone:ROME}).format(d).replace(/^./,c=>c.toUpperCase());}
function measureTime(s){
 const direct=s.updated||s.temperatureAt||s.windAt;if(direct)return direct;
 const m=String(s.updatedText||"").match(/(\d{1,2})\/(\d{1,2})\/(\d{2,4}).*?(\d{1,2}):(\d{2})/);
 if(!m)return null;const year=Number(m[3])<100?2000+Number(m[3]):Number(m[3]);
 return new Date(year,Number(m[2])-1,Number(m[1]),Number(m[4]),Number(m[5])).toISOString();
}
function stale(s){const d=when(measureTime(s));return d?(Date.now()-d.getTime())>60*60000:false;}
function rainText(s){if(finite(s.rainRate))return `🌧️ ${fmt(s.rainRate)} mm/h`;if(finite(s.precipitation))return `🌧️ ${fmt(s.precipitation)} mm`;if(finite(s.rainToday))return `☔ ${fmt(s.rainToday)} mm oggi`;return null;}
function stationCard(s){const online=s.status==="online",old=stale(s),rain=rainText(s);return `<button class="observed-card ${online?"":"offline"} ${old?"stale":""}" data-key="${s.key}" ${online?"":"disabled"}><div class="observed-head"><div><strong>${s.name}</strong><br><small>${finite(s.altitude)?s.altitude+" m":"quota n/d"}</small></div><small>${s.source}</small></div>${online?`<div class="observed-temp">${fmt(s.temperature)}°</div><div class="observed-metrics">${finite(s.humidity)?`<span>💧 ${fmt(s.humidity,0)}%</span>`:""}${finite(s.wind)?`<span>💨 ${fmt(s.wind)} km/h</span>`:""}${finite(s.windGust)?`<span>🌬️ ${fmt(s.windGust)} km/h</span>`:""}${rain?`<span>${rain}</span>`:""}</div><div class="observed-time">${measureTime(s)?`${old?"⚠️ Dato vecchio · ":""}${clock(measureTime(s))}`:"Ora della misura non disponibile"}</div>`:`<div class="observed-time">Dati non disponibili</div>`}</button>`;}
function detail(s){const rows=[["Temperatura",`${fmt(s.temperature)} °C`],["Percepita",`${fmt(s.feelsLike)} °C`],["Umidità",`${fmt(s.humidity,0)} %`],["Vento",`${fmt(s.wind)} km/h ${s.windDirection||""}`],["Raffica",`${fmt(s.windGust)} km/h`],["Intensità pioggia",`${fmt(s.rainRate)} mm/h`],["Pioggia oggi",`${fmt(s.rainToday)} mm`],["Neve al suolo",`${fmt(s.snowHeight)} cm`]].filter(x=>!x[1].startsWith("—"));return `<h2 class="dialog-title">${s.name}</h2><div class="dialog-sub">${finite(s.altitude)?s.altitude+" m · ":""}${s.source}<br>${measureTime(s)?`Misura delle ${clock(measureTime(s))}`:"Ora della misura non disponibile"}</div><div class="dialog-grid">${rows.map(x=>`<div><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join("")}</div>`;}
function periodCard(p){const w=p.summary?.weather||{},d=p.details||{},severe=Number(w.severity)>=90;return `<div class="period-card ${severe?"severe":""}"><div class="period-time">${p.period.replace(":00","").replace(":00","")}</div><div class="period-weather">${w.icon||"🌦️"}<small>${w.label_it||"—"}</small></div><div class="period-temp">${fmt(p.summary?.temperature_c)}°</div><div class="period-rain">☔ ${fmt(p.summary?.precipitation_probability_pct,0)}% · ${fmt(p.summary?.precipitation_mm)} mm</div>${finite(d.wind_gust_max_kmh)||finite(d.wind_gust_kmh)?`<div class="period-wind">🌬️ ${fmt(d.wind_gust_max_kmh??d.wind_gust_kmh)} km/h</div>`:""}</div>`;}
function renderForecast(){const box=$("#forecast-locations"),today=new Intl.DateTimeFormat("sv-SE",{timeZone:ROME,year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date()),now=Date.now();box.innerHTML=forecastLocations.map(l=>{const periods=(l.periods_3h||[]).filter(p=>p.date===selectedDate&&Number(p.start.slice(11,13))>=5&&Number(p.start.slice(11,13))<=20&&(selectedDate!==today||new Date(p.end).getTime()>now));return `<article class="location-card"><div class="location-head"><h3>${l.name}</h3><small>${l.provider==="open-meteo"?"ICON-D2":"meteo.report"}</small></div><div class="period-strip">${periods.length?periods.map(periodCard).join(""):'<span class="worker-status">Nessuna fascia futura disponibile</span>'}</div></article>`;}).join("");}
function renderDays(){const dates=[...new Set(forecastLocations.flatMap(l=>(l.periods_3h||[]).map(p=>p.date)))].sort().slice(0,3);if(!dates.includes(selectedDate))selectedDate=dates[0]||null;$("#day-tabs").innerHTML=dates.map(d=>`<button class="day-tab ${d===selectedDate?"active":""}" data-date="${d}">${dayLabel(d)}</button>`).join("");$("#day-tabs").querySelectorAll("button").forEach(b=>b.onclick=()=>{selectedDate=b.dataset.date;renderDays();renderForecast();});}
async function loadZone(zone){selectedZone=CFG.zones[zone]?zone:"catinaccio";const z=CFG.zones[selectedZone];document.querySelectorAll(".hike-zone").forEach(b=>b.classList.toggle("active",b.dataset.zone===selectedZone));history.replaceState(null,"",`?zona=${selectedZone}`);$("#hike-status").textContent="Aggiornamento dati…";$("#observed-grid").innerHTML="";$("#forecast-locations").innerHTML="";try{const [sr,fr]=await Promise.all([fetch(CFG.stationsUrl),fetch(`${CFG.forecastUrl}/zone/${z.forecastId}`)]);if(!sr.ok||!fr.ok)throw Error("Dati non disponibili");const [sd,fd]=await Promise.all([sr.json(),fr.json()]);stations=sd.stations||[];forecastLocations=fd.zone?.locations||[];const map=new Map(stations.map(s=>[s.key,s]));$("#observed-grid").innerHTML=z.stations.map(k=>map.get(k)).filter(Boolean).map(stationCard).join("")||'<div class="worker-status">Nessuna stazione associata</div>';$("#observed-grid").querySelectorAll("[data-key]").forEach(b=>b.onclick=()=>{const s=map.get(b.dataset.key);if(s){$("#station-dialog-body").innerHTML=detail(s);$("#station-dialog").showModal();}});selectedDate=null;renderDays();renderForecast();$("#hike-status").textContent=`${z.name} · dati aggiornati alle ${clock(sd.generatedAt)}`;$("#hike-status").className="worker-status ok";}catch(e){$("#hike-status").textContent="⚠️ Dati temporaneamente non disponibili";$("#hike-status").className="worker-status error";}}
function init(){const requested=new URLSearchParams(location.search).get("zona")||"catinaccio";$("#hike-zones").innerHTML=Object.entries(CFG.zones).map(([id,z])=>`<button class="hike-zone" data-zone="${id}">${z.name}</button>`).join("");$("#hike-zones").querySelectorAll("button").forEach(b=>b.onclick=()=>loadZone(b.dataset.zone));$(".dialog-close").onclick=()=>$("#station-dialog").close();$("#station-dialog").onclick=e=>{if(e.target===$("#station-dialog"))$("#station-dialog").close();};loadZone(requested);}
init();
